version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      # - frontend
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

  api1:
    build: ./api1-springboot
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: "mongodb+srv://<username>:<password>@<cluster-url>/<dbname>?retryWrites=true&w=majority"
    networks:
      - app-network

  api2:
    build: ./api2-express
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb+srv://<username>:<password>@<cluster-url>/<dbname>?retryWrites=true&w=majority"
    networks:
      - app-network

  # frontend:
  #   build: ./frontend-react
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
