pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    docker.image('maven:3.9.5-openjdk-17').inside('-v /var/run/docker.sock:/var/run/docker.sock') {
                        // Verificar a versão do Maven
                        sh 'mvn --version'

                        // Compilar e empacotar o projeto
                        sh 'mvn package -Dmaven.test.skip=true'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    docker.image('maven:3.9.5-openjdk-17').inside('-v /var/run/docker.sock:/var/run/docker.sock') {
                        // Executar os testes do projeto
                        sh 'mvn clean install'
                    }
                }
            }
        }
    }
}
// pipeline {
//     agent none
//         stages {
//             stage('Build') {
//                 agent {
//                     docker { image 'maven' }
//                 }
//                 steps {
//                     sh 'mvn package Dmaven.test.skip=true'
//                 }
//             }
//             stage('Test') {
//                 agent {
//                     docker { image 'maven' }
//                 }
//                 steps {
//                     sh 'mvn clean install'
//                 }
//             }
//         }
// }

